version: "3.9"

services:
  app:
    build: .
    container_name: marketplace_api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: marketplace_db
      DB_SSLMODE: disable
      DB_TIMEZONE: UTC
    volumes:
      - ./migrations:/root/migrations